# Generated by Django 5.0.6 on 2024-06-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_amount_issueitem_issued_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='initial_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
