# Generated by Django 5.0.6 on 2024-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_issueitem_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockitem',
            name='initial_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
